### ISSUE TITLE
[Bug report] react-md-editor list 스타일 안나오는 에러 해결

### ISSUE THREAD

**Issue by scs0209** [scs0209/myBlog#14]
## 내용
react-md-editor로 글을 작성하는데 list 스타일이 안나오는 문제
### 원인
Tailwind CSS를 사용하면서 @tailwind base에서 발생하는 문제, 기본 스타일 설정으로 인해 ul과 il 태그의 list-style이 적용되지 않는 문제
```css
ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```
### 해결 방법
1. index.css 파일에서 아래와 같이 코드를 작성하여 기본적으로 제공하는 list-style 복원
```css
 @layer base {
  ul,
  ol {
    list-style: revert;
  }
}
```
2. 필요한 ul 태그에 직접 Tailwind CSS 클래스를 추가하여 list-style 적용
```
list-disc list-inside
```
 나는 첫 번째 방법을 사용

해당 에러에 대한 문제 해결 방법이 담긴 링크
https://stackoverflow.com/questions/69276276/why-tailwind-list-style-type-is-not-working
